version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "deps(pub)"
    groups:
      pub-dependencies:
        patterns:
          - "*"
