name: komodo_go
description: "Flutter app to control Komodo infrastructure management platform."
publish_to: 'none'
version: 0.2.2+10

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^3.2.0
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.1
  hooks_riverpod: ^3.2.0
  json_annotation: ^4.10.0
  lucide_icons_flutter: ^3.1.9
  riverpod: any
  riverpod_annotation: ^4.0.1
  shared_preferences: ^2.5.4
  skeletonizer: ^2.1.2
  syntax_highlight: ^0.5.0
  url_launcher: ^6.3.2
dev_dependencies:
  build_runner: ^2.10.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  image: ^4.7.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.12.0
  mocktail: ^1.0.4
  patrol: ^4.1.0
  riverpod_generator: ^4.0.2
  test_api: any
  very_good_analysis: ^10.0.0
dependency_overrides:
  test_api: 0.7.9 # To-Do: Remove this override with the next flutter upgrade (if new flutter version uses test_api >=0.7.9)


patrol:
  test_directory: integration_test

flutter:
  uses-material-design: true
  assets:
    - assets/komodo-go-logo.png
    - assets/komodo-go-logo_rounded.png
    - assets/komodo-go-logo_circle.png
    - assets/demo_mode/ui_defined_stack/compose.yml

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/komodo-go-logo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/komodo-go-logo.png
  web:
    generate: true
    image_path: assets/komodo-go-logo.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/komodo-go-logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/komodo-go-logo.png

flutter_native_splash:
  color: "#014226"
  image: assets/komodo-go-logo_rounded.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#014226"
    image: assets/komodo-go-logo_rounded.png
