name: komodo_go
description: "Flutter app to control Komodo infrastructure management platform."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^14.8.1
  hooks_riverpod: ^3.0.0
  json_annotation: ^4.9.0
  lucide_icons_flutter: ^3.1.9
  riverpod_annotation: ^3.0.0
  shared_preferences: ^2.5.3
  syntax_highlight: ^0.5.0
  skeletonizer: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  image: ^4.5.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  patrol: ^4.1.0
  riverpod_generator: ^3.0.0
  very_good_analysis: ^7.0.0

patrol:
  test_directory: integration_test

flutter:
  uses-material-design: true
  assets:
    - assets/komodo-go-logo.png
    - assets/komodo-go-logo_rounded.png
    - assets/komodo-go-logo_circle.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/komodo-go-logo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/komodo-go-logo.png
  web:
    generate: true
    image_path: assets/komodo-go-logo.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/komodo-go-logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/komodo-go-logo.png

flutter_native_splash:
  color: "#014226"
  image: assets/komodo-go-logo_rounded.png
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#014226"
    image: assets/komodo-go-logo_rounded.png
